[package]
name = "thread_pool"
version = "0.1.0"
authors = ["vsimoes"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
